services:
#  backend:
#    build:
#      context: ./backend
#      dockerfile: Dockerfile
#    container_name: backend
#    ports:
#      - "8080:8080"
#    environment:
#      MONGO_URI: mongodb://mongo:27017/workshopepsi  # Connect to the "mongo" service
#    depends_on:
#      - mongo  # Ensure mongo is running before starting the backend

  mongo:
    image: mongo:latest
    container_name: mongo-db
    ports:
      - "27017:27017"  # Expose MongoDB to external network
    environment:
      MONGO_INITDB_DATABASE: workshopepsi

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    ports:
      - "8081:8081"  # Expose Mongo Express on port 8081
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo  # Connect to the "mongo" service
      ME_CONFIG_BASICAUTH_USERNAME: ''
      ME_CONFIG_BASICAUTH_PASSWORD: ''
    depends_on:
      - mongo  # Ensure mongo is running before starting mongo-express
